function [fitresult, gof] = createFit(T2, utslag_1)
%CREATEFIT(T2,UTSLAG_1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : T2
%      Y Output: utslag_1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Sep-2020 15:57:00


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( T2, utslag_1 );

% Set up fittype and options.
ft = fittype( 'poly8' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'utslag_1 vs. T2', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel T2
ylabel utslag_1
grid on


